/*

Este es un configurador de la base de datos. Asegurense de tener instalado Mysql

Ejecuten con
node configurar-mysql.js

Brian Craig
*/

var config = require('./configuracion.js'); 

var mysql      = require('mysql');

var connection = mysql.createConnection({
  host     : config['mysql-host'],
  user     : config['mysql-usuario'],
  password : config['mysql-clave'],
  database : config['mysql-db']
});


connection.connect(function(err) {
  if(err) throw "No se pudo conectar a la BD. asegurese de que MySQL este corriendo, y que la configuracion en nodejs/configuracion.js sea la correcta"
});

//crear tabla usuarios
connection.query("CREATE TABLE `usuarios` (`dominio` varchar(200) NOT NULL,`titulo` varchar(200) DEFAULT NULL,`footer` varchar(500) DEFAULT NULL,`id` int(11) DEFAULT NULL,`version` int(11) DEFAULT NULL,`visitas` bigint(20) DEFAULT NULL,`menu` varchar(1000) DEFAULT NULL,`tema` varchar(100) DEFAULT NULL,`home-id` int(11) DEFAULT NULL,PRIMARY KEY (`dominio`), UNIQUE KEY `dominio_UNIQUE` (`dominio`)) ENGINE=InnoDB DEFAULT CHARSET=utf8")
//crear tabla vistas
connection.query("CREATE TABLE `vistas` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `datos` text,  PRIMARY KEY (`id`),  UNIQUE KEY `idvistas_UNIQUE` (`id`)) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8");

connection.query("INSERT INTO `proyecto`.`usuarios`(`dominio`,`titulo`,`footer`,`id`,`version`,`visitas`,`menu`,`tema`,`home-id`) VALUES ('127.0.0.1', 'Industria Gráfica', 'Remedios Escalada de San Martín 325, C.A.B.A. - Tel.: (011)4855-3130 - (011) 4855-4741', '0', '0', '0', '[[\"Quienes Somos\",\"quienes-somos\",1],[\"Nuestro Servicio\",\"nuestro-servicio\",2],[\"Presupuesto\",\"presupuesto\",3],[\"Que imprimimos\",\"que-imprimimos\",4]]', 'Simple y Elegante - Brian Craig', '1');");

connection.query("INSERT INTO `proyecto`.`vistas`(`id`,`datos`)VALUES('1', '<h1>Quienes somos</h1>       <p>En dos columnas de 42 LINEAS, fue concebido el primer libro impreso, La Biblia de Mazarino o Biblia de 42 lineas, en el siglo XV, por Johanes Gutenberg, en Magnucia , Alemania.</p>        <p>El nombre  Biblia de 42 LINEAS se refiere al numero de lineas impresas en cada pagina. Su produccion dio comienzo a la impresion masiva de textos y tiene el status de icono como el comienzo de la “Edad de la Imprenta”.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>    <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>      <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>        <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>        <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>     <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>        <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>       <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>');");
connection.query("INSERT INTO `proyecto`.`vistas`(`id`,`datos`)VALUES('2', '<h1>Nuestro servicio :D</h1>       <p>En dos columnas de 42 LINEAS, fue concebido el primer libro impreso, La Biblia de Mazarino o Biblia de 42 lineas, en el siglo XV, por Johanes Gutenberg, en Magnucia , Alemania.</p>        <p>El nombre  Biblia de 42 LINEAS se refiere al numero de lineas impresas en cada pagina. Su produccion dio comienzo a la impresion masiva de textos y tiene el status de icono como el comienzo de la “Edad de la Imprenta”.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>    <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>      <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>        <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>        <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>     <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>        <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>       <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>');");
connection.query("INSERT INTO `proyecto`.`vistas`(`id`,`datos`)VALUES('3', '<h1>Presupuesto</h1>       <p>En dos columnas de 42 LINEAS, fue concebido el primer libro impreso, La Biblia de Mazarino o Biblia de 42 lineas, en el siglo XV, por Johanes Gutenberg, en Magnucia , Alemania.</p>        <p>El nombre  Biblia de 42 LINEAS se refiere al numero de lineas impresas en cada pagina. Su produccion dio comienzo a la impresion masiva de textos y tiene el status de icono como el comienzo de la “Edad de la Imprenta”.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>    <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>      <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>        <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>        <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>     <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>        <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>       <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>');");
connection.query("INSERT INTO `proyecto`.`vistas`(`id`,`datos`)VALUES('4', '<h1>Que imprimimos</h1>       <p>En dos columnas de 42 LINEAS, fue concebido el primer libro impreso, La Biblia de Mazarino o Biblia de 42 lineas, en el siglo XV, por Johanes Gutenberg, en Magnucia , Alemania.</p>        <p>El nombre  Biblia de 42 LINEAS se refiere al numero de lineas impresas en cada pagina. Su produccion dio comienzo a la impresion masiva de textos y tiene el status de icono como el comienzo de la “Edad de la Imprenta”.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>    <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>      <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>       <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>        <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>        <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>     <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>        <p>XI siglos despues y de una tercera generacion de gráficos, quisimos dar homenaje al nacimiento de esta noble profesion  y en 1990 nace 42 LINEAS, actualmente una de las mayores imprentas comerciales de Buenos Aires, en Tecnologia aplicada en todos los procesos de preimpresion,  impresion y terminacion.</p>       <p>Somos una imprenta lider en trabajos que junto a la calidad, demandan rapidez, buen precio y un excelente servicio.</p>');");


connection.end();

console.log("parece ser que todo fue bien ( a menos que te aparezcan mil errores ) Brian Craig")
